# Header
menu:
    Избраное: tag:избранное
    Читаю: tag:читаю
    rss:  /rss/index.xml

rss: /rss/index.xml

# all posts with this tag will be marked
favorite_tag: избранное

# use smart timestamps like 'a minute a ago'
fancy_dates: true

email: f@f213.in
copyright_years: 2015
social: true

# show section with titles of other posts in the post page
readmore: true

# show neighbor posts at the post page
neighbours: true

# Miscellaneous
favicon: /favicon.ico
apple_touch_icon: /apple-touch-icon.png
