# Header
menu:
    Избраное: tag:избранное
    Читаю: tag:читаю
    rss:  /rss/index.xml

# all posts with this tag will be marked
favorite_tag: избранное

email: f@f213.in
copyright_years: 2015
neighbours: true
social: true
readmore: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: